# Pre-commit configuration for MCP Handley Lab
# Minimal set of high-value hooks complementing black/ruff

repos:
  # Essential file integrity checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: debug-statements
      - id: check-ast
      - id: check-added-large-files
      - id: mixed-line-ending
      - id: trailing-whitespace

  # Python formatting and linting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.8
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  # Custom version checking (must run last)
  - repo: local
    hooks:
      - id: version-check
        name: Check for Version Bump
        entry: python scripts/check_version.py
        language: python
        additional_dependencies: ['tomli>=2.0.0']
        stages: [pre-commit]
        pass_filenames: false
