name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  version-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Need full history to compare with master
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"
        
    - name: Install packaging
      run: |
        python -m pip install --upgrade pip
        pip install packaging
    
    - name: Check version bump
      run: |
        python scripts/check_version_bump.py

  test:
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"
        cache: 'pip'
        cache-dependency-path: |
          pyproject.toml
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    
    - name: Setup Rust toolchain
      uses: dtolnay/rust-toolchain@stable
    
    - name: Cache cargo binaries
      uses: actions/cache@v3
      with:
        path: ~/.cargo/bin
        key: ${{ runner.os }}-cargo-bin-code2prompt
        
    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        cache-targets: false
        cache-on-failure: true
    
    - name: Install code2prompt
      run: |
        # Check if code2prompt is already cached
        if ! command -v code2prompt &> /dev/null; then
          cargo install code2prompt
        fi
        
    - name: Test with pytest
      run: |
        python -m pytest tests/ --cov=mcp_handley_lab --cov-report=xml --cov-report=term-missing -v
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
        
  build:
    runs-on: ubuntu-latest
    needs: [version-check, test]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"
        
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
        
    - name: Build package
      run: |
        python -m build
        
    - name: Check package
      run: |
        twine check dist/*
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/