name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  version-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Need full history to compare with master
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install packaging tomli
    
    - name: Check version bump
      run: |
        git branch -a  # Debug: show available branches
        python scripts/check_version.py

  test:
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"
        cache: 'pip'
        cache-dependency-path: |
          pyproject.toml
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y mutt msmtp offlineimap3 notmuch
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    
    - name: Setup Rust toolchain
      uses: dtolnay/rust-toolchain@stable
    
    - name: Cache cargo binaries
      id: cache-cargo
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/code2prompt
          ~/.cargo/registry/cache
          ~/.cargo/git/db
        key: ${{ runner.os }}-cargo-bin-code2prompt-v2
        restore-keys: |
          ${{ runner.os }}-cargo-bin-code2prompt-
          ${{ runner.os }}-cargo-bin-
        
    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        cache-targets: false
        cache-on-failure: true
        shared-key: "code2prompt-build"
    
    - name: Debug cache status
      run: |
        echo "Cache hit: ${{ steps.cache-cargo.outputs.cache-hit }}"
        echo "Checking cache directories:"
        ls -la ~/.cargo/bin/ || echo "No ~/.cargo/bin directory"
        command -v code2prompt && echo "code2prompt found in PATH" || echo "code2prompt not in PATH"
        
    - name: Install code2prompt
      if: steps.cache-cargo.outputs.cache-hit != 'true'
      run: |
        echo "⏳ Installing code2prompt from source..."
        cargo install code2prompt
        echo "✅ code2prompt installed successfully"
        
    - name: Verify code2prompt installation
      run: |
        code2prompt --version
        
    - name: Test with pytest (VCR-backed tests only)
      env:
        GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
        GMAIL_TEST_PASSWORD: ${{ secrets.GMAIL_TEST_PASSWORD }}
        GH_TOKEN: ${{ github.token }}
      run: |
        echo "Running fast VCR-backed tests (excluding live API contract validation)"
        python -m pytest tests/ -m "not live" --cov=mcp_handley_lab --cov-report=xml --cov-report=term-missing -v
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
        
  build:
    runs-on: ubuntu-latest
    needs: [version-check, test]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"
        
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
        
    - name: Build package
      run: |
        python -m build
        
    - name: Check package
      run: |
        twine check dist/*
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/
